diet_info = {
    "proteina": "La proteína es crucial para la recuperación muscular. Recomiendo consumir entre 1.6 y 2.2 gramos por kg de peso corporal.",
    "carbohidratos": "Los carbohidratos son esenciales para el rendimiento energético. Debes consumir carbohidratos complejos como avena, arroz integral y papas.",
    "grasas": "Las grasas saludables, como las de aguacate y frutos secos, son importantes para la función hormonal.",
    "suplementos": "Los suplementos como la creatina, proteína en polvo y BCAAs pueden ser útiles para maximizar el rendimiento deportivo.",
    "hidratos": "Hidratarse adecuadamente es clave para el rendimiento. Bebe agua regularmente durante el día.",
    "micronutrientes": "Los micronutrientes son esenciales para el funcionamiento del cuerpo. Incluye frutas y verduras variadas en tu dieta.",
    "desayuno": "No omitas el desayuno; un buen desayuno mejora el rendimiento cognitivo y físico.",
    "comidas frecuentes": "Realiza comidas más pequeñas y frecuentes para mantener estables los niveles de energía.",
    "calorias": "Controlar la ingesta calórica es fundamental para alcanzar objetivos de pérdida de peso o ganancia muscular.",
    "vegetales": "Los vegetales de hoja verde son ricos en fibra y nutrientes, ideales para una alimentación balanceada.",
    "azucares añadidos": "Limita el consumo de azúcares añadidos para evitar picos de insulina y aumento de peso.",
    "snacks saludables": "Opta por snacks saludables, como yogur natural o frutos secos, para evitar alimentos procesados.",
    "horarios de comida": "Mantén horarios regulares de comida para ayudar a regular el metabolismo.",
    "porciones": "Controla las porciones para evitar el exceso calórico, utilizando platos más pequeños si es necesario.",
    "proporciones": "La proporción de macronutrientes debe ser adecuada; un enfoque común es 40% carbohidratos, 30% proteínas y 30% grasas.",
    "entrenamiento de fuerza": "El entrenamiento de fuerza es vital para aumentar la masa muscular y el metabolismo.",
    "cardio": "Incorpora ejercicio cardiovascular al menos 150 minutos a la semana para mejorar la salud del corazón.",
    "flexibilidad": "Incluye ejercicios de flexibilidad y movilidad en tu rutina para prevenir lesiones.",
    "variabilidad": "Varía tu rutina de ejercicios para evitar estancamientos y mantener la motivación.",
    "recuperacion": "La recuperación es tan importante como el entrenamiento; asegúrate de descansar adecuadamente.",
    "calentamiento": "Siempre realiza un calentamiento antes de entrenar para preparar los músculos y evitar lesiones.",
    "enfriamiento": "El enfriamiento después del ejercicio ayuda a la recuperación y disminuye la rigidez muscular.",
    "intensidad": "Aumenta gradualmente la intensidad de tus entrenamientos para mejorar el rendimiento y evitar lesiones.",
    "descanso activo": "Los días de descanso deben incluir actividad ligera, como caminar o estiramientos.",
    "frecuencia": "Entrena cada grupo muscular al menos dos veces por semana para optimizar los resultados.",
    "sueño": "El sueño adecuado es fundamental para la recuperación muscular y la regulación hormonal.",
    "estres": "Gestionar el estrés es clave; el estrés crónico puede afectar negativamente la salud y el rendimiento.",
    "apoyo social": "Contar con un sistema de apoyo social puede aumentar la adherencia a una dieta y rutina de ejercicio.",
    "registro": "Mantener un registro de alimentos y ejercicios puede ayudarte a ser más consciente de tus hábitos.",
    "motivacion": "Establecer metas realistas y alcanzables te mantendrá motivado a largo plazo.",
    "comer consciente": "Practica la alimentación consciente; presta atención a lo que comes y disfruta cada bocado.",
    "cocina en casa": "Cocinar en casa te permite controlar los ingredientes y las porciones.",
    "evitar distracciones": "Come sin distracciones (televisión, teléfono) para mejorar la conciencia de la saciedad.",
    "planificacion": "Planifica tus comidas y entrenamientos con antelación para aumentar la adherencia.",
    "evaluacion periodica": "Revisa y ajusta tus objetivos de forma periódica para mantenerte en el camino.",
    "multivitaminicos": "Un multivitamínico puede ser útil para cubrir deficiencias, pero no sustituye una dieta equilibrada.",
    "proteina en polvo": "La proteína en polvo puede ser conveniente, pero prioriza fuentes naturales siempre que sea posible.",
    "omega-3": "Los ácidos grasos omega-3 son beneficiosos para la salud cardiovascular; considera incluir pescado graso.",
    "BCAAs": "Los BCAAs pueden ayudar en la recuperación muscular, especialmente en entrenamientos intensos.",
    "vitamina D": "La vitamina D es esencial para la salud ósea; considera la suplementación si no recibes suficiente sol.",
    "cafeina": "La cafeína puede mejorar el rendimiento, pero consume con moderación para evitar efectos secundarios.",
    "creatina": "La creatina puede ayudar a aumentar la fuerza y masa muscular; es segura para la mayoría de las personas.",
    "pre-entrenos": "Los suplementos pre-entrenamiento pueden aumentar la energía, pero lee las etiquetas y evita el exceso de estimulantes.",
    "hidratos de carbono": "Los geles o bebidas de carbohidratos pueden ser útiles durante entrenamientos largos.",
    "consistencia": "La clave de la suplementación es la consistencia; no esperes resultados inmediatos.",
    "dieta personalizada": "Cada persona es única; adapta tu dieta a tus necesidades, preferencias y objetivos.",
    "intolerancias": "Considera las intolerancias alimentarias y alérgicas al diseñar tu plan de alimentación.",
    "dieta ciclica": "Las dietas cíclicas pueden ser efectivas para algunas personas, permitiendo un enfoque flexible.",
    "calculo de macronutrientes": "Calcula tus macronutrientes según tu objetivo: pérdida de peso, mantenimiento o ganancia muscular.",
    "adaptacion": "Adapta tu rutina de ejercicios y dieta a los cambios en tu cuerpo y estilo de vida.",
    "paciencia": "Los resultados requieren tiempo; mantén la paciencia y la constancia.",
    "percepcion de la saciedad": "Escucha a tu cuerpo y aprende a reconocer las señales de hambre y saciedad.",
    "autocompasion": "Sé amable contigo mismo; un desliz ocasional no arruinará tu progreso.",
    "mentalidad de crecimiento": "Adopta una mentalidad de crecimiento; cada desafío es una oportunidad para aprender.",
    "celebra logros": "Celebra tus logros, por pequeños que sean, para mantenerte motivado.",
    "consultar a un profesional": "Consulta a un dietista o nutricionista antes de hacer cambios drásticos en tu dieta.",
    "tecnica adecuada": "Asegúrate de utilizar la técnica adecuada en los ejercicios para prevenir lesiones.",
    "escuchar a tu cuerpo": "Si sientes dolor o malestar, detén el ejercicio y evalúa la situación.",
    "evaluacion medica": "Realiza un chequeo médico antes de comenzar un nuevo programa de ejercicio, especialmente si tienes condiciones preexistentes.",
    "evitar extremismos": "Evita enfoques extremos en la dieta o el ejercicio; busca un equilibrio sostenible.",
    "entorno social": "El entorno social puede influir en tus elecciones alimentarias; elige ambientes que fomenten hábitos saludables.",
    "salidas y eventos": "Planifica con anticipación tus elecciones en eventos sociales para mantener tus objetivos.",
    "cocina multicultural": "Explora diferentes cocinas saludables para mantener la variedad en tu dieta.",
    "estacionalidad": "Consume alimentos de temporada para asegurar frescura y calidad.",
    "cultura y tradicion": "Integra alimentos de tu cultura y tradiciones en tu dieta de manera equilibrada.",
    "monitoreo de progreso": "Registra tus progresos regularmente para ajustar tu plan según sea necesario.",
    "uso de aplicaciones": "Considera usar aplicaciones de seguimiento de alimentos y ejercicios para mantenerte enfocado.",
    "evaluacion de metas": "Revisa tus metas trimestralmente y ajusta según tu progreso.",
    "feedback": "Busca feedback de entrenadores o amigos para obtener una perspectiva externa sobre tu progreso."
}